export const greetings = {
  arab: 'أهلا بك',
  chinese: '欢迎',
  italian: 'Benvenuto',
  checz: 'Vítejte',
  korean: '어서 오십시오',
  // kurd: 'Bi xêr hatî',
  // danish: 'Velkommen',
  // hebrew: 'ברוך הבא',
  // french: 'Bienvenu',
  // georgian: 'მოგესალმებით',
  // spanish: 'Bienvenidos',
  // portog: 'Bem-vindo',
  // russian: 'Добро пожаловать',
  // turkish: 'Hoş geldin',
  // japanese: 'いらっしゃいませ',
}
