export const greetings = [
  'ٱلسَّلَامُ عَلَيْكُمْ',
  'नमस्ते',
  'Vanakkam',
  'God morgen',
  'Mangwanani',
  'ٱلسَّلَامُ عَلَيْكُمْ',
  'नमस्ते',
  'Vanakkam',
  'God morgen',
  'Mangwanani',
  'ٱلسَّلَامُ عَلَيْكُمْ',
  'नमस्ते',
  'Vanakkam',
  'God morgen',
  'Mangwanani',
  'ٱلسَّلَامُ عَلَيْكُمْ',
  'नमस्ते',
  'Vanakkam',
  'God morgen',
  'Mangwanani',
  'ٱلسَّلَامُ عَلَيْكُمْ',
  'नमस्ते',
  'Vanakkam',
  'God morgen',
  'Mangwanani',
  'ٱلسَّلَامُ عَلَيْكُمْ',
  'नमस्ते',
  'Vanakkam',
  'God morgen',
  'Mangwanani',
]
